// Auto-generated by generateGlassRegistry.ts
import GlassActivityIndicator from './GlassActivityIndicator.vue'
import GlassApp from './GlassApp.vue'
import GlassAppBar from './GlassAppBar.vue'
import GlassAppIcon from './GlassAppIcon.vue'
import GlassAudioPlayer from './GlassAudioPlayer.vue'
import GlassButton from './GlassButton.vue'
import GlassCalendar from './GlassCalendar.vue'
import GlassCheckbox from './GlassCheckbox.vue'
import GlassCircularGauge from './GlassCircularGauge.vue'
import GlassClock from './GlassClock.vue'
import GlassColorPicker from './GlassColorPicker.vue'
import GlassComboBox from './GlassComboBox.vue'
import GlassContainer from './GlassContainer.vue'
import GlassDatePicker from './GlassDatePicker.vue'
import GlassDigitalClock from './GlassDigitalClock.vue'
import GlassDropdownColorPicker from './GlassDropdownColorPicker.vue'
import GlassFooter from './GlassFooter.vue'
import GlassInfiniteScroll from './GlassInfiniteScroll.vue'
import GlassInfiniteScrollWrapper from './GlassInfiniteScrollWrapper.vue'
import GlassInput from './GlassInput.vue'
import GlassList from './GlassList.vue'
import GlassModal from './GlassModal.vue'
import GlassPanel from './GlassPanel.vue'
import GlassProgressBar from './GlassProgressBar.vue'
import GlassRadio from './GlassRadio.vue'
import GlassSelect from './GlassSelect.vue'
import GlassSheet from './GlassSheet.vue'
import GlassSidebar from './GlassSidebar.vue'
import GlassSlider from './GlassSlider.vue'
import GlassTabStrip from './GlassTabStrip.vue'
import GlassTextarea from './GlassTextarea.vue'
import GlassThemeChooser from './GlassThemeChooser.vue'
import GlassTimePicker from './GlassTimePicker.vue'
import GlassToggle from './GlassToggle.vue'
import GlassWindow from './GlassWindow.vue'

import { ClickOutside } from '../directives/clickOutside'

export const GlassComponents = {
  GlassActivityIndicator,
  GlassApp,
  GlassAppBar,
  GlassAppIcon,
  GlassAudioPlayer,
  GlassButton,
  GlassCalendar,
  GlassCheckbox,
  GlassCircularGauge,
  GlassClock,
  GlassColorPicker,
  GlassComboBox,
  GlassContainer,
  GlassDatePicker,
  GlassDigitalClock,
  GlassDropdownColorPicker,
  GlassFooter,
  GlassInfiniteScroll,
  GlassInfiniteScrollWrapper,
  GlassInput,
  GlassList,
  GlassModal,
  GlassPanel,
  GlassProgressBar,
  GlassRadio,
  GlassSelect,
  GlassSheet,
  GlassSidebar,
  GlassSlider,
  GlassTabStrip,
  GlassTextarea,
  GlassThemeChooser,
  GlassTimePicker,
  GlassToggle,
  GlassWindow,
};

// Vue 3 Plugin Install Function
export default {
  install(app) {
    app.directive('click-outside', ClickOutside);  
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
  }, 
};
