// Auto-generated by generateGlassRegistry.ts
import AnalogClock from './AnalogClock.vue'
import AppHeader from './AppHeader.vue'
import AppleGlassModal from './AppleGlassModal.vue'
import ClockDigit from './ClockDigit.vue'
import ClockSeparator from './ClockSeparator.vue'
import FlipDigit from './FlipDigit.vue'
import GeoClock from './GeoClock.vue'
import GlassAppView from './GlassAppView.vue'
import GlassButton from './GlassButton.vue'
import GlassCalendar from './GlassCalendar.vue'
import GlassCheckbox from './GlassCheckbox.vue'
import GlassColorPalette from './GlassColorPalette.vue'
import GlassColorPicker from './GlassColorPicker.vue'
import GlassDatePicker from './GlassDatePicker.vue'
import GlassDigitalClock from './GlassDigitalClock.vue'
import GlassDropdown from './GlassDropdown.vue'
import GlassDropdownContainer from './GlassDropdownContainer.vue'
import GlassFlipClock from './GlassFlipClock.vue'
import GlassFooter from './GlassFooter.vue'
import GlassGauge from './GlassGauge.vue'
import GlassInput from './GlassInput.vue'
import GlassPanel from './GlassPanel.vue'
import GlassPopup from './GlassPopup.vue'
import GlassProgressBar from './GlassProgressBar.vue'
import GlassRadioGroup from './GlassRadioGroup.vue'
import GlassRadioItem from './GlassRadioItem.vue'
import GlassSidebar from './GlassSidebar.vue'
import GlassSlider from './GlassSlider.vue'
import GlassTabStrip from './GlassTabStrip.vue'
import GlassTextarea from './GlassTextarea.vue'
import ThemeToggle from './ThemeToggle.vue'
import TimePicker from './TimePicker.vue'

import { clickOutside } from '../directives/clickOutside'

export const GlassComponents = {
  AnalogClock,
  AppHeader,
  AppleGlassModal,
  ClockDigit,
  ClockSeparator,
  FlipDigit,
  GeoClock,
  GlassAppView,
  GlassButton,
  GlassCalendar,
  GlassCheckbox,
  GlassColorPalette,
  GlassColorPicker,
  GlassDatePicker,
  GlassDigitalClock,
  GlassDropdown,
  GlassDropdownContainer,
  GlassFlipClock,
  GlassFooter,
  GlassGauge,
  GlassInput,
  GlassPanel,
  GlassPopup,
  GlassProgressBar,
  GlassRadioGroup,
  GlassRadioItem,
  GlassSidebar,
  GlassSlider,
  GlassTabStrip,
  GlassTextarea,
  ThemeToggle,
  TimePicker,
};

// Vue 3 Plugin Install Function
export default {
  install(app) {
    app.directive('click-outside', clickOutside);  
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
  }, 
};
