// Auto-generated by generateGlassRegistry.ts
import GlassApp from './GlassApp.vue'
import GlassAppBar from './GlassAppBar.vue'
import GlassButton from './GlassButton.vue'
import GlassCalendar from './GlassCalendar.vue'
import GlassCheckbox from './GlassCheckbox.vue'
import GlassClock from './GlassClock.vue'
import GlassComboBox from './GlassComboBox.vue'
import GlassContentPanel from './GlassContentPanel.vue'
import GlassDatePicker from './GlassDatePicker.vue'
import GlassDigitalClock from './GlassDigitalClock.vue'
import GlassInput from './GlassInput.vue'
import GlassModal from './GlassModal.vue'
import GlassPanel from './GlassPanel.vue'
import GlassSelect from './GlassSelect.vue'
import GlassSidebar from './GlassSidebar.vue'
import GlassSlider from './GlassSlider.vue'
import GlassTabStrip from './GlassTabStrip.vue'
import GlassTextarea from './GlassTextarea.vue'
import GlassThemeChooser from './GlassThemeChooser.vue'
import GlassTimePicker from './GlassTimePicker.vue'
import GlassToggle from './GlassToggle.vue'

export const GlassComponents = {
  GlassApp,
  GlassAppBar,
  GlassButton,
  GlassCalendar,
  GlassCheckbox,
  GlassClock,
  GlassComboBox,
  GlassContentPanel,
  GlassDatePicker,
  GlassDigitalClock,
  GlassInput,
  GlassModal,
  GlassPanel,
  GlassSelect,
  GlassSidebar,
  GlassSlider,
  GlassTabStrip,
  GlassTextarea,
  GlassThemeChooser,
  GlassTimePicker,
  GlassToggle,
};

// Vue 3 Plugin Install Function
export default {
  install(app) {
    Object.keys(GlassComponents).forEach((name) => {
      app.component(name, GlassComponents[name]);
    });
  }, 
};
